### PR TITLE
Add Forward Arrow Icons

### PR DESCRIPTION
**Pull request by eddiesarevalo**
## 🗒️ Summary
Added arrow forward and arrow forward up icons.
Screenshot 2024-06-27 at 9 31 28 AM
Screenshot 2024-06-27 at 9 31 45 AM

Use current color fill for circle and white fill for the arrow.

Also includes several dependabot updates from main.

## ⚙️ Test Data and/or Report
run `npm run build:icons`

## ♻️ Related Issues
refs https://github.com/NASA-PDS/portal-wp-tasks/issues/72

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
LGTM 👍

**Review by anilnatha — CHANGES_REQUESTED** [review]
Hey @eddiesarevalo , it's my opinion that we shouldn't be adding styling to the iconography. In this case the circle that wraps the icons. In addition, the icons themselves are duplicates of the existing `arrow-right` and `arrow-diagonal`.

I think I understand what you were trying to achieve with these, namely the integration of the icon with a filled circle for use in a button; however, that implementation should be performed in wds-react.

Should we have a discussion about this?

**Comment by eddiesarevalo** [comment]
Hey @anilnatha Arrow diagonal and Arrow right are different from these icons with a circle are you saying it is up to wds-react to implement the arrow circle icons? And not to use svg but to use css styling?

I guess my confusion on this icon is why is this icon used extensively in the designs but not included here? Are we to have 2 different sets of icons. Some for the wds and some for wds-react? Shouldn't we just hand out the circle arrow icons in wds? Or are we implying that circle arrow icons are only good in react but not in any other js framework?

**Comment by anilnatha** [comment]
Spoke with Eddie about the icons added in this PR. We will reuse the existing icons and create the buttons with the needed styles in `wds-react`. Closing the PR as it's no longer needed.

**Pull request closed without merging**
